title: Guo Guangxin's Homepage
page-top-title: Guo Guangxin
top-section-bg-text:  "Welcome to Guangxin Guo's academic personal website \n 欢迎来到郭广信的学术主页 \n Stardust-seeking stars"
home-subtitle: Guo Guangxin&ensp;|&ensp;郭广信
copyright-text: '&copy; Guo Guangxin 2023-2025. All Rights Reserved.'
