title: Guo Guangxin's Homepage
page-top-title: Guo Guangxin
top-section-bg-text: Stardust-seeking stars
home-subtitle: Guo Guangxin&ensp;|&ensp;郭广信
copyright-text: '&copy; Guo Guangxin 2023-2025. All Rights Reserved.'
