title: Guo Guangxin's Homepage
page-top-title: Guo Guangxin
top-section-bg-text:  Welcome to Guangxin Guo's academic  website  欢迎来到郭广信的学术主页  Stardust-seeking stars
home-subtitle: Guo Guangxin &ensp;|&ensp;郭卷卷
copyright-text: '&copy; Guo Guangxin 2023-2025. All Rights Reserved.'
